version: 2
jobs:
  build:
    docker:
    - image: docker.mirror.hashicorp.services/circleci/golang:1.12
    working_directory: /go/src/github.com/hashicorp/vault-plugin-auth-cf
    steps:
    - checkout
    - run:
        name: "Setup Environment"
        command: |
          echo 'export GO111MODULE=on' >> $BASH_ENV
    - run:
        name: "Run Tests"
        command: |
          make test
    - run:
        name: "Install Gox"
        command: go get github.com/mitchellh/gox
    - run:
        name: "Run Test Build"
        command: |
          make dev
